/*
 FusionCharts JavaScript Library
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @version fusioncharts/3.3.1-sr1.19666
*/
FusionCharts(["private","modules.renderer.js-gradientlegend",function(){function M(c,d,ja){var f=c[0],a=c[1],c=c[2];f+=(d[0]-f)*ja;a+=(d[1]-a)*ja;d=c+(d[2]-c)*ja;return{hex:(B+(f<<16|a<<8|d).toString(16)).slice(-6),rgb:[f,a,d]}}function k(c,d){return c.maxvalue-d.maxvalue}function O(c){var d=c.colorRange||{},f=c.dataMin,a=c.dataMax,e=c.sortLegend||!1,i=c.mapByCategory||!1,l=c.defaultColor,Q=c.numberFormatter,g=d.color,c=this.colorArr=[],h,t,F,b,A;this.mapByCategory=i;if(d.mapbypercent==="1")this.mapbypercent=
!0;if(d.gradient==="1"&&!i){this.gradient=!0;h=v(Z(d.startcolor,d.mincolor,d.code));e=R(v(Z(h,l,"CCCCCC")));i=this.scaleMin=H(d.startvalue,d.minvalue,this.mapbypercent?0:f);c.push({code:h,maxvalue:i,label:X(d.startlabel),codeRGB:R(h)});if(g&&(t=g.length))for(f=0;f<t;f+=1)l=g[f],h=v(Z(l.color,l.code)),b=H(l.value,l.maxvalue),A=H(l.minvalue),b>i&&c.push({code:h,maxvalue:b,userminvalue:A,label:X(Z(l.label,l.displayvalue)),codeRGB:R(h)});c.sort(k);t=c.length;for(f=1;f<t;f+=1)l=c[f],h=l.maxvalue-i,h>0?
(l.minvalue=i,l.range=h,i=l.maxvalue):(c.splice(f,1),f-=1,t-=1);if(c.length>=2)this.scaleMax=i,c[f-1].label=Z(d.endlabel,c[f-1].label,c[f-1].displayvalue);if(c.length===1)b=H(d.maxvalue,this.mapbypercent?100:a),c.push({minvalue:i,maxvalue:b,range:b-i,label:d.endlabel}),this.scaleMax=b,delete c[0].code;d=c[0];a=c[c.length-1];if(!d.code||!a.code){t=ka(e);t={minRGB:ga((t[2]=0,t)),maxRGB:ga((t[2]=100,t))};if(!d.code)d.codeRGB=t.minRGB,d.code=aa(t.minRGB);if(!a.code)a.codeRGB=t.maxRGB,a.code=aa(t.maxRGB)}t=
c.length;for(f=1;f<t;f+=1)if(l=c[f],l.code){if(F){a=l;A=d.maxvalue;for(g=a.maxvalue-A;F<f;F+=1)e=c[F],h=M(d.codeRGB,a.codeRGB,(e.maxvalue-A)/g),e.code=h.hex,e.codeRGB=h.rgb}F=null;d=l}else F=F||f;if(this.scaleMin===void 0||this.scaleMax===void 0)this.noValidRange=!0}else if(g&&(t=g.length)){for(f=0;f<t;f+=1)l=g[f],h=Z(l.color,l.code),b=H(l.maxvalue),A=H(l.minvalue),F=Z(l.label,l.displayvalue,i?w:Q.dataLabels(A)+" - "+Q.dataLabels(b)),(h&&b>A||i&&F)&&c.push({code:h,maxvalue:b,minvalue:A,label:X(F),
labelId:F.toLowerCase()});c.length?e&&c.sort(k):this.noValidRange=!0}}function P(c,d){return d?j(c*100)/100+f:ba(c,w).toString()}var C=this.hcLib,a=window,a=/msie/i.test(navigator.userAgent)&&!a.opera,H=C.pluckNumber,B=C.COLOR_BLACK,e=C.COLOR_GLASS,U=C.FC_CONFIG_STRING,ea=C.graphics,ga=ea.HSBtoRGB,ka=ea.RGBtoHSB,aa=ea.RGBtoHex,R=ea.HEXtoRGB,s=C.COMMASTRING,w=C.BLANKSTRING,X=C.parseUnsafeString,ha=C.graphics.convertColor,ra=C.POSITION_TOP,S=C.POSITION_MIDDLE,la=C.POSITION_START,oa=C.POSITION_END,sa=
C.graphics.getDarkColor,ma=C.graphics.getLightColor,Z=C.pluck,ba=C.getValidValue,ia=C.toRaphaelColor,j=Math.round,o=Math.max,m=Math.min,c=Math.abs,f="%",d="rgba(192,192,192,"+(a?0.002:1.0E-6)+")",v=function(c){return c&&c.replace(/^#?([a-f0-9]+)/ig,"$1")};O.prototype={getColorObj:function(c){var d=this.colorArr,f=this.gradient?1:0,a=d[f];if(this.mapByCategory){for(c=X(c).toLowerCase();a;){if(a.labelId===c)return{code:a.code,seriesIndex:f};f+=1;a=d[f]}return{outOfRange:!0}}else if(this.gradient)if(this.scaleMin<=
c&&this.scaleMax>=c){for(;a&&a.maxvalue<c;)f+=1,a=d[f];c=(c-a.minvalue)/a.range;return{code:M(d[f-1].codeRGB,a.codeRGB,c).hex}}else return{outOfRange:!0};else{for(;a;){if(a.maxvalue>c&&a.minvalue<=c)return{code:a.code,seriesIndex:f};f+=1;a=d[f]}if((a=d[f-1])&&a.maxvalue===c)return{code:a.code,seriesIndex:f-1};return{outOfRange:!0}}}};O.prototype.constructor=O;C.colorRange=O;var Q=C.configureGradientLegendOptions=function(c,d){var f=c.legend,a=d.chart;f.legendSliderBorderWidth=H(a.legendpointerborderthickness,
1);f.legendSliderBorderColor=ha(Z(a.legendpointerbordercolor,B),H(a.legendpointerborderalpha,100));f.legendSliderWidth=H(a.legendpointerwidth,a.legendpointerswidth,12);f.legendSliderHeight=H(a.legendpointerheight,a.legendpointersheight,12);f.legendColorBoxBorderColor=f.borderColor;f.legendColorBoxBorderWidth=f.borderWidth;f.legendScaleColor=ha(Z(a.legendscalelinecolor,B),H(a.legendscalelinealpha,100));f.legendScalePadding=H(a.legendscalepadding,4);f.legendScaleLineThickness=H(a.legendscalelinethickness,
1);f.legendScaleTickDistance=H(a.legendscaletickdistance,6);f.itemStyle.cursor="default";f.interActivity=H(a.interactivelegend,1)};C.placeGLegendBlockRight=function(c,d,f,a,e){C.configureLegendOptions(c,d.chart,!0,e,f);Q(c,d);var e=c[U].smartLabel,i=c.legend,l,v,g=i.textPadding=2,h=g*2,t=i.title.padding,F=0,b=0,A=2*i.padding,d=H(d.chart.legendpadding,7)+i.borderWidth/2+1,u=c.colorRange||{},fa=u.colorArr,pa=u.mapbypercent,E=u.scaleMin,$=u.scaleMax-E,q=i.legendSliderWidth,x=i.legendSliderHeight/2;v=
i.legendScalePadding;var p=i.legendScaleTickDistance,K=i.itemStyle||{};l=H(parseInt(K.lineHeight,10)||12);var y=l*0.75,r=f-A,G,k,z=0,s,j,B,I,L,S,da;a-=A;if(!u.noValidRange&&fa&&(k=fa.length)>1){k-=1;if(i.title.text!==w)e.setStyle(i.title.style),l=e.getSmartText(i.title.text,r,o(l,a/4)),i.title.text=l.text,F=l.width+A,a-=b=l.height+t;e.setStyle(K);l=e.lineHeight;r-=p+v+q;i.colorBoxX=q;t=o(l,r/2);r=m(r-t-4,l);s=o(l,a/2);G=a/4;p=fa[0];p.scaleLabel=P(p.maxvalue,pa);l=e.getSmartText(p.label,G,r);p.label=
l.text;K=l.height;p.labelY=y-l.height/2;v=e.getSmartText(p.scaleLabel,t,s);p.scaleLabel=v.text;u=v.height/2;j=v.width;p.scaleLabelY=y-v.height/2;i.colorBoxY=o(u,l.width+h,x)+b;p=da=fa[k];p.scaleLabel=P(p.maxvalue,pa);l=e.getSmartText(p.label,G,r);p.label=l.text;K=o(K,l.height);p.labelY=y-l.height/2;v=e.getSmartText(p.scaleLabel,t,s);p.scaleLabel=v.text;j=o(j,v.width);G=v.height/2;l=o(l.width+h,G,x);p.scaleLabelY=y-v.height/2;i.colorBoxHeight=x=a-i.colorBoxY-l;s=x-G;B=x/$;L=m(x-z,s-u)-4;for(G=1;G<
k;G+=1)p=fa[G],I=(p.maxvalue-E)*B,l=e.getSmartText(p.label,m(I-z,x-I)*2,r),p.label=l.text,K=o(K,l.height),p.labelY=y-l.height/2,l=l.width/2,p.scaleLabel=P(p.maxvalue,pa),v=e.getSmartText(p.scaleLabel,t,m(I-u,s-I)*2),p.scaleLabel=v.text,j=o(j,v.width),S=v.height/2,p.scaleLabelY=y-v.height/2,L=m(L,(I-o(S+u,l+z)-4)*$/p.range),z=l+I,u=S+I;L=o(m(L,(m(s-u,x-z)-4)*$/da.range,a*0.3),0);i.colorBoxHeight-=L;i.colorBoxWidth=K&&K+h||15;i.height=i.totalHeight=a+b+A-L;i.width=(j&&j+g)+i.colorBoxWidth+q+i.legendScaleTickDistance+
i.legendScalePadding+A;if(i.width<F)i.colorBoxX+=(F-i.width)/2,i.width=F;if(i.width>f)i.width=f;d+=i.width;c.chart.marginRight+=d;return d}else return i.enabled=!1,0};C.placeGLegendBlockBottom=function(c,d,f,a,e){C.configureLegendOptions(c,d.chart,!1,e,f);Q(c,d);var e=c[U].smartLabel,i=c.legend,l,v,g=i.textPadding=2,h=i.title.padding,t=0,F=0,b=2*i.padding,d=H(d.chart.legendpadding,7)+i.borderWidth/2+1,A=c.colorRange||{},u=A.colorArr,fa=A.mapbypercent,pa=A.scaleMin,E=A.scaleMax-pa,$=i.legendSliderWidth,
q=i.legendSliderHeight,x=i.legendScalePadding,p=i.legendScaleTickDistance,K=i.itemStyle||{};l=H(parseInt(K.lineHeight,10)||12);var y=l*0.75,r=a-b,G,s,z,k,j=0,B,I,L;f-=b;if(!A.noValidRange&&u&&(s=u.length)>1){s-=1;if(i.title.text!==w)e.setStyle(i.title.style),l=e.getSmartText(i.title.text,f,r/3),i.title.text=l.text,t=l.width+b,r-=F=l.height+h;e.setStyle(K);l=e.lineHeight;r-=p+x+q;h=o(l,r/2);K=m(r-h-4,l);G=f/4;k=G*2;z=u[0];z.scaleLabel=P(z.maxvalue,fa);l=e.getSmartText(z.label,G,K);z.label=l.text;r=
l.height;z.labelY=y-l.height/2;v=e.getSmartText(z.scaleLabel,k,h);z.scaleLabel=v.text;x=v.width/2;p=v.height;if(!z.code)z.code=Z(i.minColor,"CCCCCC");i.colorBoxX=o(x,l.width+g,$);z=A=u[s];z.scaleLabel=P(z.maxvalue,fa);l=e.getSmartText(z.label,G,K);z.label=l.text;r=o(r,l.height);z.labelY=y-l.height/2;v=e.getSmartText(z.scaleLabel,k,h);z.scaleLabel=v.text;p=o(p,v.height);z=v.width/2;l=o(l.width+g,z,$);i.colorBoxWidth=$=f-i.colorBoxX-l;k=$-z;B=$/E;L=m($-j,k-x)-4;for(G=1;G<s;G+=1)z=u[G],I=(z.maxvalue-
pa)*B,l=e.getSmartText(z.label,m(I-j,$-I)*2,K),z.label=l.text,r=o(r,l.height),z.labelY=y-l.height/2,l=l.width/2,z.scaleLabel=P(z.maxvalue,fa),v=e.getSmartText(z.scaleLabel,m(I-x,k-I)*2,h),z.scaleLabel=v.text,p=o(p,v.height),v=v.width/2,L=m(L,(I-o(v+x,l+j)-4)*E/z.range),j=l+I,x=v+I;L=o(m(L,(m(k-x,$-j)-4)*E/A.range,f*0.3),0);i.colorBoxWidth-=L;i.width=f+b-L;if(i.width<t)i.colorBoxX+=(t-i.width)/2,i.width=t;i.colorBoxY=F+q;i.colorBoxHeight=r&&r+2*g||15;i.height=i.totalHeight=(p&&p+g)+i.colorBoxHeight+
F+q+i.legendScaleTickDistance+i.legendScalePadding+b;if(i.height>a)i.height=a;d+=i.height;c.chart.marginBottom+=d;return d}else return i.enabled=!1,0};var G=function(){return{point:this}};C.rendererRoot.drawGradientLegendItem=function(f){var a=this,v=a.paper,Q=a.options,k=a.canvasLeft,i=a.canvasTop,l=a.canvasWidth,m=a.canvasHeight,g=Q.colorRange,h,t,F,b,A=Q.legend,u=H(A.padding,4),fa=A.itemStyle;parseInt(fa.fontSize,10);var Q=A.symbolStyle,pa=A.interActivity,E=f.elements,f=E.elementGroup,$=A.layout===
"vertical",q,x,p,K,y,r,ta=0,o=A.lighting3d,z,C,V=A.colorBoxX,M=A.colorBoxY,I=z=A.colorBoxWidth,L=C=A.colorBoxHeight,P={FCcolor:{color:w,alpha:w,angle:0,ratio:w}},da=P.FCcolor;V+=u;var u=M+u,W,T,M=A.legendColorBoxBorderColor,Ba=A.legendColorBoxBorderWidth,na=["M"],Ca=A.legendScaleColor;r=A.legendScalePadding;var ba=A.legendScaleLineThickness,O=ba%2/2;t=A.legendScaleTickDistance;var R=A.legendSliderWidth,X=A.legendSliderHeight;y=L/2;b=I/2;var U=R/2,Y=X/2,aa,ca,qa;T=0;var ua=ma("ABABAB",50),va=sa("ABABAB",
70),A=ha("ABABAB",100),va=ha(va,100),ua=ha(ua,100),xa,N={isFirst:!0},J={},ea,ga,wa,ka;if(g&&(h=g.colorArr)&&(F=h.length)>1){N.toolText=ea=p=g.scaleMin;J.toolText=ga=g=g.scaleMax;K=g-p;N.snapPX=J.snapPX=0;N.tooltipConstraint=J.tooltipConstraint="chart";N.getLabelConfig=J.getLabelConfig=G;N.tooltipPos=[0,0];J.tooltipPos=[0,0];J.tooltipOffsetReference=N.tooltipOffsetReference={};J.tooltipOffsetReference.left=N.tooltipOffsetReference.left+=k-20;J.tooltipOffsetReference.top=N.tooltipOffsetReference.top+=
i;wa=E.colorBox=v.group("colorBox",f);if($){N.tooltipPos[0]=J.tooltipPos[0]=l+k;T=270;da.angle=90;k=V-R;l=V+I;i=u-Y;q=u+Y;k=j(V-R)+0.5;l=j(V)+0.5;i=j(u-Y)+0.5;q=j(u+Y)+0.5;aa=j(V+I)+0.5;qa=j(u-2)+0.5;x=j(u+2)+0.5;W=j(u)+0.5;m=V-U/2;ca=j(m-Y)+0.5;m=j(m)+0.5;y=u-Y/2;Y=j(y+Y)+0.5;y=j(y)+0.5;z/=2;U=["M",k,i,"L",l,i,l,qa,aa,W,l,x,l,q,k,q,"Z","M",ca,y,"L",m,y,"M",ca,W,"L",m,W,"M",ca,Y,"L",m,Y];Y=["M",k+1,i,"L",k+1,q,"M",ca,y-1,"L",m,y-1,"M",ca,W-1,"L",m,W-1,"M",ca,Y-1,"L",m,Y-1];y=V+I+r;q=j(y+t)+O;y=j(y)+
O;W=V+b;ca=F-1;for(t=0;t<F;t+=1)b=h[t],l=(b.maxvalue-p)/K,x=L*l+u,r=j(x)+O,t?(da.ratio+=s,da.color+=s,da.alpha+=s,na.push("L",y,r,q,r,"M",y,r),t===ca?(m=oa,r=x+2):(m=S,r=x)):(na.push(y,r,"L",q,r,"M",y,r),m=la,r=x-2),da.ratio+=(l-ta)*100,da.color+=Z(b.code,B),da.alpha+=Z(b.alpha,100),ta=l,b.legendItem=v.text(f).attr({text:b.label,x:W,y:r,"text-anchor":m,"vertical-align":S}).rotate(T,W,r).css(fa),b.legendSymbol=v.text(f).attr({text:b.scaleLabel,x:q,y:x,"text-anchor":la,"vertical-align":S}).css(fa);
N.xMin=J.xMin=0;N.xMax=J.xMax=0;N.yMin=J.yMin=0;N.yMax=J.yMax=L;N.x=J.x=0;N.y=0;J.y=L;h=X+I;F=R}else{N.tooltipPos[1]=J.tooltipPos[1]=m+i;k=j(V-U)+0.5;l=j(V+U)+0.5;i=j(u-X)+0.5;q=j(u+L)+0.5;aa=j(V-2)+0.5;m=j(V+2)+0.5;ca=j(V)+0.5;qa=j(u)+0.5;x=u-Y/2;W=j(x-Y)+0.5;x=j(x)+0.5;T=V-U/2;b=j(T+U)+0.5;T=j(T)+0.5;C/=2;U=["M",k,i,"L",l,i,l,qa,m,qa,ca,q,aa,qa,k,qa,"Z","M",T,W,"L",T,x,"M",ca,W,"L",ca,x,"M",b,W,"L",b,x];Y=["M",k,i+1,"L",l,i+1,"M",T-1,W,"L",T-1,x,"M",ca-1,W,"L",ca-1,x,"M",b-1,W,"L",b-1,x];r=u+L+
r;T=j(r+t)+O;r=j(r)+O;x=u+y;ca=F-1;for(t=0;t<F;t+=1)b=h[t],l=(b.maxvalue-p)/K,q=I*l+V,y=j(q)+O,t?(da.ratio+=s,da.color+=s,da.alpha+=s,na.push("L",y,r,y,T,"M",y,r),t===ca?(m=la,y=q+2):(m=S,y=q)):(na.push(y,r,"L",y,T,"M",y,r),m=oa,y=q-2),da.ratio+=(l-ta)*100,da.color+=Z(b.code,B),da.alpha+=Z(b.alpha,100),ta=l,b.legendItem=v.text(f).attr({text:b.label,x:y,y:x,"text-anchor":m,"vertical-align":S}).css(fa),b.legendSymbol=v.text(f).attr({text:b.scaleLabel,x:q,y:T,"text-anchor":S,"vertical-align":ra}).css(fa);
N.xMin=J.xMin=0;N.xMax=J.xMax=I;N.yMin=J.yMin=0;N.yMax=J.yMax=0;N.y=J.y=0;N.x=0;J.x=I;h=R;F=X+L}E.colorBox=v.rect(wa).attr({x:V,y:u,width:I,height:L,fill:ia(P),stroke:M,strokeWidth:Ba});if(o)E.colorBoxEffect=v.rect(wa).attr({x:V,y:u,width:z,height:C,fill:e,"stroke-width":0});E.scale=v.path(f).attr({path:na,stroke:Ca,"stroke-width":ba});xa=function(b,g,h,c,d){var f;$?(f=g*K/L+p,c=g>0?c:c+g+0.01):(f=b*K/I+p,h=b>0?h:h+b+0.01);b=j(f*100)/100;d?(E.slider1.translate(h,c),E.slider1Effect.translate(h,c),
E.slider1Tracker.toFront().translate(h,c).tooltip(b,null,null,!0),ea=f):(E.slider2.translate(h,c),E.slider2Effect.translate(h,c),E.slider2Tracker.toFront().translate(h,c).tooltip(b,null,null,!0),ga=f);pa&&(ka=clearTimeout(ka),ka=setTimeout(function(){a.setScaleRange&&a.setScaleRange(ea,ga)},100))};sliderDragging=function(b,g){var h,d=h=0,f,t=this.isFirst,a=t?J:N;if($){d=this._startY+g;d<=0&&(d=0);d>L&&(d=L);if(t?d>a.y:d<a.y)d=a.y;if(c(d-this.y)>=(this.snapPX||0))f=!0}else{h=this._startX+b;h<=0&&(h=
0);h>I&&(h=I);if(t?h>a.x:h<a.x)h=a.x;if(c(h-this.x)>=(this.snapPX||0))f=!0}if(f)xa(h,d,h-this.x,d-this.y,t),this.x=h,this.y=d};sliderDragStart=function(){this._startX=this.x;this._startY=this.y};sliderDragEnd=function(){};o=j(p*100)/100;E.slider1=v.path(f).attr({path:U,fill:A,strokeWidth:1,stroke:va});E.slider1Effect=v.path(f).attr({path:Y,fill:"none",strokeWidth:1,stroke:ua});E.slider1Tracker=v.rect(f).attr({ishot:!0,width:h,height:F,x:k,y:i,fill:d,stroke:"none"}).drag(sliderDragging,sliderDragStart,
sliderDragEnd,N,N,N).tooltip(o,null,null,!0).css(Q);o=j(g*100)/100;E.slider2=v.path(f).attr({path:U,fill:A,strokeWidth:1,stroke:va}).translate(J.x,J.y);E.slider2Effect=v.path(f).attr({path:Y,fill:"none",strokeWidth:1,stroke:ua}).translate(J.x,J.y);E.slider2Tracker=v.rect(f).attr({ishot:!0,width:h,height:F,x:k,y:i,fill:d,stroke:"none"}).translate(J.x,J.y).css(Q).drag(sliderDragging,sliderDragStart,sliderDragEnd,J,J,J).tooltip(o,null,null,!0)}}}]);
FusionCharts(["private","modules.renderer.js-annotations",function(){var M=this.core,k=this.hcLib,O=window,P=/msie/i.test(navigator.userAgent)&&!O.opera,C=k.addEvent,a=k.removeEvent,H=(O=k.hasTouch)?6:5,B="rgba(192,192,192,"+(P?0.002:1.0E-6)+")",P=Math,e=P.min,U=P.max,ea=P.sin,ga=P.cos,ka=P.PI,aa=ka/180,R=this.extend,s=k.pluck,w=k.pluckNumber,X=k.graphics.convertColor,ha=k.getValidValue,ra=k.parseUnsafeString,S=k.setImageDisplayMode,la=k.graphics.parseColor,oa=k.setLineHeight,sa={style:{}},ma=k.toRaphaelColor,
Z=function(c,f){return{start:-f,end:-c,angle:c-f}},ba=function(c,f,d,a){var e=0,G=0,f=f===void 0||f===null?1:f,n;if(!c||!c.toString)return d;c=c.toLowerCase().replace(/\s/g,"");if(d=c.match(/^[\+\-]?\d+(\.\d+)?|[\+\-]\d+(\.\d+)?/g)){for(n=0;n<d.length;n+=1)e+=Number(d[n])||0;e*=f}if(d=c.match(/^[\+\-]?(\$[a-z]+)|[\+\-](\$[a-z]+)/g))for(n=0;n<d.length;n+=1)G+=a[d[n]]||0;if(d=c.match(/^[\+\-]?\$\d+(\.\d+)?|[\+\-]\$\d+(\.\d+)?/g))for(n=0;n<d.length;n+=1)G=G+Number(d[n].replace("$",""))||0;return e+G},
ia=function(c){var f=this.__state.annotationGroupsById;(c=f&&f[c])&&c.wrapper&&c.wrapper.show()},j=function(c){var f=this.__state.annotationGroupsById;(c=f&&f[c])&&c.wrapper&&c.wrapper.hide()},o,m;o=function(c,f,d,a){this.options=c;this.chart=d;this.attrs={};this.css={};this.bounds={};this.shared=f;this.snaps=a||{};this.id=c.id||"";this.items=[];this.setup();this.scale()};R(o.prototype,{scaleImageX:1,scaleImageY:1,scaleText:1,scaleValue:1,scaleValueComplement:1,scaleX:1,scaleY:1});o.prototype.setup=
function(){var c=this.options;this.isBelow=s(c.showbelow,c.showbelowchart,this.shared.showbelow)!="0";this.useTracker=!this.isBelow&&this.chart.trackerGroup&&this.shared.useTracker};o.prototype.scale=function(){var c=this.options,f=this.chart,d=this.shared,a=this.bounds,e=this.snaps,G=d.rootxscale,n=d.rootyscale,k=a.xs=w(c.xscale,d.xscale,100)/100,m=a.ys=w(c.yscale,d.yscale,100)/100,j,D,i;this.scaleText*=m;this.scaleImageX*=k;this.scaleImageY*=m;if(s(c.autoscale,d.autoscale)!="0")k=w(c.origw,d.origw),
m=w(c.origh,d.origh),k=f.chartWidth/k,m=f.chartHeight/m,f=s(c.constrainedscale,d.constrainedscale)!="0",j=k<m?k:m,D=f?j:k,i=f?j:m,this.scaleValue*=j,this.scaleValueComplement*=f?j:k<m?m:k,this.scaleX*=D,this.scaleY=this.scaleX*i,a.xs*=D,a.ys*=i,G*=D,n*=i,s(c.scaletext,d.scaletext)=="1"&&(this.scaleText*=i),s(c.scaleimages,d.scaleimages)=="1"&&(this.scaleImageX*=D,this.scaleImageY*=i);a.x=ba(s(c.x,c.xpos),G,0,e)+w(c.grpxshift,d.grpxshift,0);a.y=ba(s(c.y,c.ypos),n,0,e)+w(c.grpyshift,d.grpyshift,0);
this.xshift=w(c.xshift,d.xshift,0);this.yshift=w(c.yshift,d.yshift,0)};o.prototype.draw=function(){var c=this.chart,f=this.options,d=this.bounds,a=this.items,e=c.layers.dataset,k=this.wrapper;if(!k)this.wrapper=k=c.paper.group("annotations"),e&&(this.isBelow?k.insertBefore(e):k.insertAfter(c.layers.datalabels||e));for(this.wrapper.attr({x:0,y:0,visibility:f.visible=="0"?"hidden":""}).translate(d.x,d.y);d=a.unshift();)d.remove();if(f=f.items){d=0;for(e=f.length;d<e;d+=1)a.push((new m(c,f[d],this)).draw())}return this};
o.prototype.destroy=function(){for(var c=this.wrapper,f=this.items,d;d=f.shift();)d.destroy();if(c)this.wrapper=c.remove()};m=function(c,f,d){var a=!1,e;this.chart=c;this.options=f;this.group=d;this.args=[];this.attrs={};this.attrsTracker={};this.style={};this.bounds={};this.type=f.type&&f.type.toLowerCase&&f.type.toLowerCase();for(e in m.eventNames)typeof f[e]==="function"&&(this[e]=f[e],a=!0);this.hasEvents=a;if(typeof f.onload==="function")this.onload=f.onload;this.scale();this.setup()};m.prototype.getAbsoluteBounds=
function(){var c=this.bounds,f=c.x1,d=c.y1,a=c.x2,Q=c.y2,k=e(f,a),n=e(d,Q),f=U(f,a)-k,d=U(d,Q)-n;return{x:k,width:f,y:n,height:d,r:c.r,unscaled:{width:f/c.xs,height:d/c.ys}}};m.prototype.scale=function(){var c=this.group,f=c.bounds,d=this.bounds,a=this.options,e=c.snaps,k=s(a.x,a.xpos),n=s(a.y,a.ypos),m=s(a.tox,a.toxpos),j=s(a.toy,a.toypos),o=d.xs=f.xs,f=d.ys=f.ys,D=w(a.xshift,c.xshift,0),i=w(a.yshift,c.yshift,0);this.hasDimensionY=this.hasDimensionX=this.hasDimension=!0;d.x1=ba(k,o,0,e)+D;m===void 0?
(this.hasDimensionX=this.hasDimension=!1,d.x2=d.x1):d.x2=ba(m,o,0,e)+D;d.y1=ba(n,f,0,e)+i;j===void 0?(this.hasDimensionY=this.hasDimension=!1,d.y2=d.y1):d.y2=ba(j,f,0,e)+i;d.r=w(a.radius,0)*c.scaleValue};m.prototype.setup=function(){var c=this.options,a=this.group,d=a.options,e=this.attrs,k=this.style,m=a.scaleValue,n=w(d.fillalpha,d.alpha,100),j=this.fillAlpha=s(c.fillalpha,c.alpha,n),o=this.fillColor=s(c.fillcolor,c.color,d.color,"#ff0000"),C=this.fillPattern=s(c.fillpattern&&c.fillpattern.toLowerCase&&
c.fillpattern.toLowerCase(),d.fillpattern&&d.fillpattern.toLowerCase&&d.fillpattern.toLowerCase()),D=c.showborder?c.showborder=="1":ha(c.bordercolor),n=this.borderAlpha=w(c.borderalpha,c.alpha,d.borderalpha,n),i=this.dashed=c.dashed=="1";this.link=s(c.link,d.link);this.shadow=s(c.showshadow,d.showshadow)=="1";e.stroke=D?X(s(c.bordercolor,o),n):"none";e["stroke-linecap"]="round";this.fillOptions={gradientUnits:"objectBoundingBox",color:o,alpha:j,ratio:s(c.fillratio,d.fillratio),angle:360-w(c.fillangle,
0),radialGradient:C==="radial"};e["stroke-width"]=D?w(c.borderthickness,c.thickness,2)*m:0;i&&(e["stroke-dasharray"]=[w(c.dashlen,5)*m,w(c.dashgap,3)*m]);if(this.link)k.cursor="pointer",k._cursor="hand";this.useTracker=a.useTracker;this.toolText=ra(s(c.tooltext,d.tooltext));if(this.useTracker||this.link||this.toolText)R(this.attrsTracker,{stroke:B,fill:B}),this.link&&(this.attrsTracker.ishot=+new Date)};m.prototype.draw=function(){var c=this.chart,f=this.type,d=this.attrs,e=this.style,k=c.paper,j=
m.types[f]&&m.types[f].call&&m.types[f].call(this),n=j==="image",s=j==="text",w=n||s,o=this.link||this.toolText,D=this.wrapper,f=this.tracker,i=c.layers.tracker||this.group.wrapper,l=!1,B,g=m.eventNames,h,t;if(j){if(D)if(D.elemType!==j)D=D.remove();else if(this.hasEvents)for(h in g)if((t=this[h])&&t.eventAttached)a(B.node,g[h],t),t.eventAttached=!1;if(!n&&d.fill===void 0)d.fill=ma(this.fillOptions);D?D.attr(d).css(e):(this.args.push(this.group.wrapper),D=this.wrapper=k[j].apply(k,this.args).attr(d).css(e),
D.elemType=j,l=!0,this.args.pop());this.shadow&&!this.shadowAdded&&!n&&!s?D.shadow(this.shadowAdded=!0,U(this.borderAlpha,this.fillOptions.alpha)/100):D.shadow(this.shadowAdded=!1);if(o){if(this.useTracker){if(!f)this.args.push(i),f=this.tracker=w?k.rect(0,0,0,0,0,i):k[j].apply(k,this.args),this.args.pop();f.attr(d).attr(this.attrsTracker)}}else f&&(f=f.remove());B=this.tracker||D;this.link&&B.click(c.linkClickFN,this);this.toolText&&B.tooltip(this.toolText||"");if(this.hasEvents)for(h in g)if((t=
this[h])&&!t.eventAttached)C(B.node,g[h],t,this),t.eventAttached=!0;n||(f&&w&&(c=D.getBBox(),f.attr({x:c.x,y:c.y,width:c.width,height:c.height})),l&&this.onload&&this.onload(d))}return this};m.prototype.destroy=function(){var c=this.wrapper;if(c)this.tracker&&this.tracker.remove(),this.wrapper=c.remove()};m.eventNames={onmouseover:O?"touchstart":"mouseover",onmouseout:"mouseout",onmousemove:O?"touchmove":"mousemove",onclick:"click"};m.textAlignOptions={left:"start",right:"end",center:"middle"};m.textVerticalAlignOptions=
{top:"bottom",middle:"middle",bottom:"top"};m.textRotationOptions={0:"0",1:"270",right:"90",left:"270"};m.types={rectangle:function(){var c=this.args,a=this.getAbsoluteBounds(),d=a.width*0.5;if(a.r>d)a.r=d;c[0]=a.x;c[1]=a.y;c[2]=a.width;c[3]=a.height;c[4]=a.r;return"rect"},line:function(){var c=this.options,a=this.group.scaleValue,d=this.attrs,e=this.bounds;this.args[0]=["M",e.x1,e.y1,"L",e.x2,e.y2];d.stroke=X(this.fillColor,this.fillAlpha);d["stroke-width"]=w(c.thickness,2)*a;d["stroke-width"]===
1&&(d["shape-rendering"]="crisp");d["stroke-width"]<H&&(this.attrsTracker["stroke-width"]=H);this.attrsTracker["stroke-dasharray"]="solid";return"path"},polygon:function(){var c=this.args,a=this.options,d=this.bounds;c[0]=w(a.sides,5);c[1]=d.x1;c[2]=d.y1;c[3]=d.r;c[4]=w(a.startangle,0);c[5]=0;return"polypath"},circle:function(){var c=this.args,a=this.options,d=this.bounds,e=this.chart.chartWidth,k=this.chart.chartHeight,m=this.group.scaleValueComplement,n=Z(w(a.startangle,0),w(a.endangle,360)),j=
d.r,o;if(!s(a.radius))d.r=e<k?e*d.xs:k*d.ys,d.r=j=d.r*0.3;a=w(a.yradius,j/m)*m;if(!this.fillPattern)this.fillOptions.radialGradient=!0,this.fillPattern="radial";if(this.fillPattern==="radial")this.fillOptions.cx=this.fillOptions.cy=0.5;if(!(n.angle%360)&&j===a)return c[0]=d.x1,c[1]=d.y1,c[2]=d.r,"circle";n.angle%360||(n.start-=0.001);k=n.start*aa;e=n.end*aa;n=n.angle*aa;m=d.x1;o=d.y1;d=m+ga(k)*j;k=o+ea(k)*a;m+=ga(e)*j;e=o+ea(e)*a;c[0]=["M",d,k,"A",j,a,0,0,n>=ka?0:1,m,e,"Z"];return"path"},arc:function(){var c=
this.options,a=this.args,d=this.bounds,e=this.chart.chartWidth,k=this.chart.chartHeight,m=this.group.scaleValue,n=Z(w(c.startangle,0),w(c.endangle,360));if(!s(c.radius))d.r=e<k?e*d.xs:k*d.ys,d.r*=0.3;d.innerR=w(c.innerradius,d.r*0.8/m)*m;if(d.innerR>d.r)d.innerR+=d.r,d.r=d.innerR-d.r,d.innerR-=d.r;if(!this.fillPattern)this.fillOptions.radialGradient=!0,this.fillPattern="radial";if(this.fillPattern==="radial")this.fillOptions.cx=this.fillOptions.cy=0.5;a[0]=d.x1;a[1]=d.y1;a[2]=d.r;a[3]=d.innerR;a[4]=
n.start*aa;a[5]=n.end*aa;return"ringpath"},text:function(){var c=this.chart,a=this.args,d=this.style,e=this.attrs,k=this.group,j=this.bounds,n=this.options,o=this.getAbsoluteBounds(),C=s(n.align,k.options.textalign,"center").toLowerCase(),B=s(n.valign,k.options.textvalign,"middle").toLowerCase(),D=ra(s(n.text,n.label)),i=this.chart&&this.chart.logic&&this.chart.logic.smartLabel,l=s(n.wrap,k.options.wraptext)=="1",H,g,h=s(n.rotatetext,k.options.rotatetext,"0").toLowerCase(),h=m.textRotationOptions[h],
t=h!="0"?"y":"x",F=c.options.orphanStyles,c=R({},F.defaultStyle.style||{}),F=F[k.id.toLowerCase()]||sa,c=R(c,F.style),F=parseFloat(c.fontSize),b=s(n.font,k.options.font,c.fontFamily),k=w(n.fontsize,k.options.fontsize,F)*k.scaleText;l&&(H=w(n.wrapwidth,this.hasDimensionX?o.width/j.xs:void 0),g=w(n.wrapheight,this.hasDimensionY?o.height/j.ys:void 0),H&&(H*=j.xs),g&&(g*=j.ys));d.fontFamily=b;d.fontWeight=s(n.bold,n.isbold)=="1"?"bold":"normal";if(s(n.italic,n.isitalic)=="1")d.fontStyle="italic";n.bgcolor&&
(!e["text-bound"]&&(e["text-bound"]=[]),e["text-bound"][0]=la(n.bgcolor));n.bordercolor&&(!e["text-bound"]&&(e["text-bound"]=[]),e["text-bound"][1]=la(n.bordercolor),e["text-bound"][2]=w(n.borderthickness,1),e["text-bound"][3]=w(n.padding,1));if(n.fontcolor)e.fill=la(n.fontcolor);d.fontSize=k+"px";k==F?d.lineHeight=c.lineHeight:oa(d);e["text-anchor"]=m.textAlignOptions[C]||m.textAlignOptions.center;i.setStyle(d);d=i.getSmartText(D,H,g,!1);e["vertical-align"]=m.textVerticalAlignOptions[B]||m.textVerticalAlignOptions.middle;
e["text-anchor"]===m.textAlignOptions.left?o[t]+=w(n.leftmargin,0):e["text-anchor"]===m.textAlignOptions.center&&(o[t]+=w(n.leftmargin,0)*0.5);if(h!=="0")e.rotation=[parseFloat(h),o.x,o.y];a[0]=o.x;a[1]=o.y;a[2]=d.text;d.tooltext&&(e.title=d.tooltext);delete e.stroke;delete e["stroke-weight"];return"text"},image:function(){var c=this,a=c.chart,d=c.style,e=a.chartWidth,k=a.chartHeight,a=c.options,m=c.attrs,j=c.args,o=ha(a.url),C=c.group.scaleImageX*s(Number(a.xscale),100)/100,B=c.group.scaleImageY*
s(Number(a.yscale),100)/100,D=c.getAbsoluteBounds(),i={width:1,height:1},l;if(!o)return j[0]=D.x,j[1]=D.y,j[2]=D.width,j[3]=D.height,j[4]=D.r,"rect";l=new Image;l.onload=function(){i=S("none","top","left",100,0,e,k,l);delete i.x;delete i.y;i=R(i,{width:(c.hasDimensionX?D.unscaled.width:i.width)*C,height:(c.hasDimensionY?D.unscaled.height:i.height)*B});setTimeout(function(){var a,g,h;if(a=c.wrapper){a.attr(i);if(g=c.tracker)h=a.getBBox(),g.attr({x:h.x,y:h.y,width:h.width,height:h.height});a.css({opacity:d.opacity=
U(w(c.fillAlpha,c.borderAlpha),c.borderAlpha)/100})}c.onload&&c.onload(i)},0)};l.src=o;j[0]=o;j[1]=D.x;j[2]=D.y;j[3]=(c.hasDimensionX?D.unscaled.width:i.width)*C;j[4]=(c.hasDimensionY?D.unscaled.height:i.height)*B;d.opacity=U(w(c.fillAlpha,c.borderAlpha),c.borderAlpha)/100;delete m.stroke;delete m.fill;delete m["stroke-linecap"];return"image"}};k.rendererRoot.callbacks.unshift(function(a){var e=a.chartInstance,d=e.__state,k=a.dataObj||{},j=k.annotations,m=a.hcJSON,n={},C,B;if(!a.drawAnnotations||
!e.dataReady()||!k.chart||!(k.chart.showannotations!="0"&&j&&j.groups&&j.groups.length)){if(!m||!m.annotations)return;j=m.annotations;if(j.options)n=j.options}else delete j.id;if(!d.annotationStores)d.annotationStores=[];d.annotationStores.push(e=j.id||"annotations");e=this[e]=[];n=R({showbelow:s(j.showbelow,j.showbelowchart),autoscale:j.autoscale,scaletext:j.scaletext,scaleimages:j.scaleimages,constrainedscale:j.constrainedscale,origw:s(j.origw,k.chart.origw,this.chartWidth),origh:s(j.origh,k.chart.origh,
this.chartHeight),xshift:j.xshift,yshift:j.yshift,grpxshift:j.grpxshift,grpyshift:j.grpyshift,xscale:j.xscale,yscale:j.yscale,rootxscale:w(j.xscale,100)/100,rootyscale:w(j.yscale,100)/100},n);if(a.snapLiterals){C=a.snapLiterals;a={};for(B in C)a["$"+B]=a["+$"+B]=C[B],a["-$"+B]=C[B]*-1;C=a}d.annotationGroupsById||(d.annotationGroupsById={});for(a=0;a<j.groups.length;a+=1)e.push(B=(new o(j.groups[a],n,this,C)).draw()),B.id&&d.annotationGroupsById&&!this.forExport&&(d.annotationGroupsById[B.id]&&d.annotationGroupsById[B.id].destroy(),
d.annotationGroupsById[B.id]=B)});M.addEventListener("rendered",function(a,e){if(e.renderer==="javascript"){var d=a.sender,k=d.jsVars||{},m=k.instanceAPI;if(!k.hcObj||!m||!m.drawAnnotations)delete d.showAnnotation,delete d.hideAnnotation;else{if(!d.showAnnotation)d.showAnnotation=d.ref.showAnnotation=ia;if(!d.hideAnnotation)d.hideAnnotation=d.ref.hideAnnotation=j}}});M.addEventListener("Initialized",function(a){var a=a.sender,e=a.__state;if(a.options.renderer==="javascript")e.annotationGroupsById=
{}});M.addEventListener("Disposed",function(a){if(a.sender.options.renderer==="javascript"){var e=a.sender,a=e.__state,e=e.jsVars.hcObj,d,k,j,m;for(m=a.annotationStores&&a.annotationStores.length||0;m--;){j=a.annotationStores[m];if(d=e&&e[j])for(;k=d.shift();)k.destroy();delete a[j]}}})}]);
FusionCharts(["private","modules.renderer.js-maps",function(){var M=this,k=M.hcLib,O,P=O=k.chartAPI,C=document,a=k.pluck,H=k.imprint,B=k.extend2,e=k.pluckNumber,U=k.pluckFontSize,ea=k.placeLegendBlockRight,ga=k.placeGLegendBlockRight,ka=k.placeGLegendBlockBottom,aa=k.placeLegendBlockBottom,R=k.HCstub,s=B(k.defaultPaletteOptions,{foregroundcolor:"333333",foregroundalpha:"100",foregrounddarkcolor:"111111",foregrounddarkalpha:"100",foregroundlightcolor:"666666",foregroundlightalpha:"100",backgroundlightcolor:"FFFFFF",
backgroundlightalpha:"100",backgroundlightangle:90,backgroundlightratio:"",backgroundcolor:"FFFFCC",backgroundalpha:"100",backgrounddarkcolor:"ffcc66",backgrounddarkalpha:"100",backgrounddarkangle:270,backgrounddarkratio:"",shadow:1}),w=k.setLineHeight,X=k.getValidValue,ha=k.parseUnsafeString,ra=k.getFirstColor,S=k.graphics.convertColor,la=k.hashify,oa=navigator.userAgent,sa=window,ma=/msie/i.test(oa)&&!sa.opera,Z=/AppleWebKit/.test(oa),ba=k.hasSVG,ia=k.FC_CONFIG_STRING,j=Math,o=j.min,m=j.max,c=j.ceil,
oa=!/fusioncharts\.com$/i.test(location.hostname),f=k.toRaphaelColor,d=function(g,a){var c;g||(g={});for(c in a)g[c]=a[c];return g},v=function(g){var a=this.parentNode;if(!a)return!1;for(;a;)if(a===C.documentElement)break;else if(a===g)return!0;else a=a.parentNode;return!1},Q=function(a,h){var c=!h?{FCcolor:a}:d(a.FCcolor,h);c.toString=f;return c},G=function(a,h){var c,d;this.index=h;for(d in a)c=s[a[d]],this[d]=c instanceof Array?c[h]:c},n={right:function(a,h){return h},left:function(a,h){return a-
h},center:function(a,h){return o(h,a-h)*2}},ya={top:function(a,h){return h},middle:function(a,h){return o(h,a-h)*2},bottom:function(a,h){return a-h}},ja=function(){if(this.hoverEntity)k.raiseEvent.apply(k,this.hoverEntityEventArgs),delete this.hoverEntityEventArgs,this.hoverEntity&&this.hoverEntityAttr&&this.hoverEntity.attr(this.hoverEntityAttr),delete this.hoverEntityAttr,this.hoverEntity=null},za=function(a,h,c,d){function b(){var b=this,a=b.entityPathMap,g=b.data,h=g&&g.length||0,c=b.items,d,
e,t,f=function(){for(e=0;h--;){if(e++>50){f();break}d=g[h];t=d.id&&d.id.toLowerCase();var A=d;delete A.outlines;delete A.label;delete A.shortlabel;delete A.labelposition;delete A.labelalignment;delete A.labelconnectors;d=A;if(t!==void 0&&a[t])c[t]=g[h].mapItem=new D(t,H(d,a[t]),u,b.group)}};f();for(d in a)c[d]||(c[d]=new D(d,a[d],u,b.group))}function e(){var b=this.items,a=[],g,h;i.push({id:"entityLabels",items:a});for(h in b)(g=b[h].getLabelObject())&&a.push(g)}if(c=c&&c.getEntityPaths()){var u=
h,f=u.options,i;if(!f.annotations)f.annotations={id:"geo",showbelow:0,autoscale:0,grpxshift:u.translateX?u.translateX:0,grpyshift:u.translateY?u.translateY:0,xscale:(u.sFactor?u.sFactor:1)*100,yscale:(u.sFactor?u.sFactor:1)*100,options:{useTracker:!0},groups:[]};i=f.annotations.groups;this.entityPathMap=c;this.data=a;this.chartObj=u;this.items={};this.group=d||h.mapGroup;b.call(this);f.entities.labelsOnTop&&e.call(this);this.drawLabels=e;this.destroy=function(){var b=this.items,a;for(a in b)b[a].destroy();
delete this.entityPathMap;delete this.data;delete this.chartObj;delete this.items;delete this.group};this.init=b;if(!u.__canvasMouseOutListenerAdded){u.__canvasMouseOutListenerAdded=!0;var E=h.paper.canvas;k.addEvent(E,"mouseout",function(b){b=b.relatedTarget;!ma||ba?(!b||!(b.ownerSVGElement&&b.ownerSVGElement===E))&&ja.call(u):b===C.documentElement||b===h.container||b===h.container.parentElement?ja.call(u):v.call(b,E)||ja.call(u)})}}},D=function(g,h,d,f){function b(){var b=this.chart.paper,a=ba||
!ma?"litepath":"path",g=this.eJSON.outlines,h=this.group,c,e;c=g&&g.length||0;if(O)for(;c--;)e=g[c],this.svgElems[c]={},this.svgElems[c].graphic=b[a](e,h).attr(R).tooltip(x).shadow(X,d.shadowLayer);else for(;c--;)e=g[c],this.svgElems[c]={},this.svgElems[c].graphic=b[a](e,h).tooltip(x).attr(R);this.addMouseGestures();return this}function A(b){var a=this.chart;a.hoverEntityEventArgs=["entityrollout",this.eventArgs,a.fusionCharts,[a.fusionCharts.id,"rollOut",this.legacyEventArgs],b];if(W&&this.isVisible)a.hoverEntity=
this,a.hoverEntityAttr=this.revertAttr,this.attr(this.hoverAttr);k.raiseEvent("entityrollover",this.eventArgs,a.fusionCharts,[a.fusionCharts.id,"rollOver",this.legacyEventArgs],b)}if(h&&d&&g!==void 0){this.chart=d;this.eJSON=h;this.group=f;this.id=g;this.originalId=h.origId;this.isVisible=!0;this.svgElems={};this.connectorElem={};var u=d.options,g=u.entities,i=g.dataLabels.style,f=g.valuesForMarkers?null:h.cleanValue,l=f===null?void 0:f,E=a(h.displayvalue,g.includeNameInLabels?g.useShortName?h.shortLabel:
h.label:""),f=this.formattedValue=h.formattedValue||"",$=g.labelSepChar,q=e(h.showtooltip,g.showTooltip),x=this.toolText=q?ha(a(h.tooltext,(g.useSNameInTooltip?h.shortLabel:h.label)+(isNaN(l)?"":g.tooltipSepChar+f))):"",p,K,y,r=e(h.showlabel,g.showLabels),o=a(h.bordercolor,g.borderColor),s=a(h.borderalpha,g.borderAlpha);y=g.scaleBorder===1;var z=e(h.borderthickness,g.borderThickness),v=a(h.labelconnectorcolor,g.connectorColor),w=a(h.labelconnectoralpha,g.connectorAlpha),B=a(h.font,i.fontFamily),C=
e(parseInt(h.fontsize,10),parseInt(i.fontSize,10)),D=a(h.fontcolor,i.color),G=e(h.labelpadding,g.labelPadding),H=g.hoverOnEmpty,W=e(h.usehovercolor,H?g.useHoverColor:isNaN(l)?0:g.useHoverColor),T=e(h.hoverborderthickness,g.hoverBorderThickness),U=e(h.fontbold,0),na=h.link,O=g.shadow,q=!ma||ba,i=d.sFactor/g.baseScaleFactor;p=d.strokeWidth;K=(q?g.baseScaleFactor:1)*p;var P=g.hiddenEntityFillObject||(g.hiddenEntityFillObject={fill:Q({color:g.hiddenEntityColor,alpha:g.hiddenEntityAlpha}).toString()}),
R,X,u=u[ia],aa=u._labelBaseWidth,ea=u._labelBaseHeight,Y=u._labelXOffset,ga=u._labelYOffset;q?(z=y?z*K:z/i)&&Z&&(z=c(z)):z=y?z*p:z;T=T===void 0?z:y?z*K:T/i;if(a(h.color,h.alpha,h.angle,h.ratio)!==void 0)q=a(h.color,g.fillColor),u=a(h.alpha,g.fillAlpha),p=a(h.angle,g.fillAngle),K=a(h.ratio,g.fillRatio),y=Q({color:q,alpha:u,angle:p,ratio:K});else{if(!g.fillColorObject)g.fillColorObject=Q({color:a(g.fillColor),alpha:a(g.fillAlpha),angle:a(g.fillAngle),ratio:a(g.fillRatio)});if(!g.emptyColorObject)g.emptyColorObject=
Q({color:a(g.emptyEntityColor),alpha:a(g.emptyEntityAlpha),angle:a(g.emptyEntityAngle),ratio:a(g.emptyEntityRatio)});y=isNaN(l)?g.emptyColorObject:g.fillColorObject;q=y.FCcolor.color;u=y.FCcolor.alpha;p=y.FCcolor.angle;K=y.FCcolor.ratio}x===""&&(q=0);R={transform:ba||!ma?"":d.transformStr,stroke:S(o,s),"stroke-width":z,fill:(this.fillColor=y).toString()};o=u.split(",");z&&o.push(s);X={scalefactor:[i,d.sFactor],opacity:m.apply(j,o)/100};if(W){if(a(h.hovercolor,h.hoveralpha,h.hoverangle,h.hoverratio)!==
void 0)q=a(h.hoverfillcolor,h.hovercolor,g.hoverFillColor),u=a(h.hoverfillalpha,h.hoveralpha,g.hoverFillAlpha),p=a(h.hoverfillangle,h.hoverangle,g.hoverFillAngle),K=a(h.hoverfillratio,h.hoverratio,g.hoverFillRatio),s=Q({color:q,alpha:u,angle:p,ratio:K});else{if(!g.hoverColorObject)g.hoverColorObject=Q({color:g.hoverFillColor,alpha:g.hoverFillAlpha,angle:g.hoverFillAngle,ratio:g.hoverFillRatio});s=g.hoverColorObject}this.hoverColor=s}!h.displayvalue&&g.includeValueInLabels&&!isNaN(l)&&(E=E===void 0?
f:E+$+f);this.value=l;this.addMouseGestures=function(){var b=this,a=b.chart,g=b.eJSON,h=b.svgElems,c;b.eventArgs={value:b.value,label:g.label,shortLabel:g.shortLabel,originalId:b.originalId||b.id,id:b.id};b.legacyEventArgs={value:b.value,lName:g.label,sName:g.shortLabel,id:b.originalId||b.id};if(W)b.hoverAttr={"stroke-width":T,fill:b.hoverColor.toString()},b.revertAttr={"stroke-width":z,fill:b.fillColor.toString()};if(!isNaN(l)||H)for(c in h)na!==void 0&&h[c].graphic.css({cursor:"pointer",_cursor:"hand"}),
h[c].graphic.node.__entity=b,h[c].graphic.click(function(a){M.raiseEvent("entityclicked",b.eventArgs,d.fusionCharts,a);na!==void 0&&d.logic.linkClickFN.call({link:na})}).hover(function(g){this.node.__entity!==a.hoverEntity&&(ja.call(b.chart),A.call(b,g))},function(){})};this.attr=function(b,a){var g=this.svgElems,h;for(h in g)g[h].graphic&&g[h].graphic.attr(b,a)};this.draw=b;this.getLabelObject=function(){var b=this,a=b.chart,g=b.eJSON,h=a.paper,c=g.labelPosition,e=g.labelAlignment,g=g.labelConnectors,
f=b.svgElems[0]&&b.svgElems[0].graphic,u,i;if(!r||!f||!E)return null;for(u=g&&g.length||0;u--;)i=g[u],b.connectorElem[u]=h.path(i,b.group).attr({transform:R.transform,stroke:S(v,w),"shape-rendering":"crisp","stroke-width":z});c?(h=c[0],g=c[1]):(c=f.getBBox(),h=c.x+c.width/2,g=c.y+c.height/2);e?(c=e[0],e=e[1],c==="right"?h-=G:c==="left"&&(h+=G),e==="top"?g-=G:e==="bottom"&&(g+=G)):(c="center",e="middle");return{x:h.toString(),y:g.toString(),wrapwidth:n[c](aa,h+Y)-G,wrapheight:ya[e](ea,g+ga)-G,wrap:1,
type:"text",align:c,valign:e,text:E,tooltext:b.toolText,link:na,bgcolor:"",bordercolor:"",fontcolor:D,fontsize:parseFloat(C)/d.sFactor,font:B,bold:U,onclick:function(a){M.raiseEvent("entityclicked",b.eventArgs,d.fusionCharts,a)},onmouseover:function(g){b!==a.hoverEntity&&(ja.call(b.chart),A.call(b,g))},ontouchstart:function(g){b!==a.hoverEntity&&(ja.call(b.chart),A.call(b,g))}}};this.destroy=function(){var b=this.svgElems,a=this.connectorElem,g;for(g in b)b[g].remove&&b[g].remove();for(g in a)a[g].destroy&&
a[g].destroy();delete this.value;delete this.formattedValue;delete this.toolText;delete this.fillColor;delete this.hoverColor;delete this.chart;delete this.group;delete this.id;delete this.isVisible;delete this.svgElems;delete this.connectorElem;delete this.renderer;delete this.options};this.show=function(){var b=this.svgElems,a;this.isVisible=!0;for(a in b)b[a].graphic&&b[a].graphic.attr(R)};this.hide=function(){var b=this.svgElems,a=this.chart,g;this.isVisible=!1;a.hoverEntity===this&&ja.call(a);
for(g in b)b[g].graphic&&b[g].graphic.attr(P)};b.call(this);g.hideEmptyEntities&&l===void 0&&this.hide()}},i=function(a,h,c){this.id=a;this.definition=h;this.application=null;this.rapi=c;if(a=c.options)this._conf=a[ia]},l=function(a,h,c,d){this.options=a;this.from=h;this.to=c;this.api=d;if(a=d.options)this._conf=a[ia]},Aa=function(a,h,c,d){this.appliedMarkers={};this.shapeObjs={};this.items={};this.connectors=[];this.options=h;this.mJSON=a;this.rapi=c;this.group=c.paper.group(d);var a=c.options,b;
if(!a.annotations)a.annotations={id:"geo",showbelow:0,autoscale:0,grpxshift:a.chart.marginLeft?a.chart.marginLeft:0,grpyshift:a.chart.marginLeft?a.chart.marginTop:0,xscale:(c.sFactor?c.sFactor:1)*100,yscale:(c.sFactor?c.sFactor:1)*100,options:{useTracker:!0},groups:[]};b=a.annotations.groups;this.setDefaultValues=function(){var b=this.options,a=this.rapi,g=b.markers,b=b.connectors,h=i.prototype,c=l.prototype;h.markerFont=g.dataLabels.style.fontFamily;h.markerFontSize=g.dataLabels.style.fontSize;h.markerFontColor=
g.dataLabels.style.fontColor;h.showMarkerTooltip=g.showTooltip;h.showMarkerLabels=g.showLabels;h.markerLabelPadding=g.labelPadding;h.labelWrapWidth=g.labelWrapWidth;h.labelWrapHeight=g.labelWrapHeight;h.labelSepChar=g.labelSepChar;h.tooltipSepChar=g.tooltipSepChar;h.fillColor=g.fillColor;h.fillAlpha=g.fillAlpha;h.fillRatio=g.fillRatio;h.fillAngle=g.fillAngle;h.startAngle=g.startAngle;h.shapeId=g.shapeId;h.borderThickness=g.borderThickness;h.borderColor=g.borderColor;h.borderAlpha=g.borderAlpha;h.markerRadius=
g.radius;h.autoScale=g.autoScale?a.sFactor:1;h.shadow=g.shadow;c.showTooltip=b.showTooltip;c.thickness=b.thickness;c.color=b.color;c.alpha=b.alpha;c.dashed=b.dashed;c.dashlen=b.dashLen;c.dashgap=b.dashGap;c.font=b.font;c.fontsize=b.fontSize;c.fontcolor=b.fontColor;c.bgcolor=b.labelBgColor;c.bordercolor=b.labelBorderColor;c.shadow=b.shadow};this.applyMarkers=function(){var a=this.mJSON.application,g=a&&a.length,h=[],c=[],d,e,f,t=this.items,i=this.appliedMarkers,k;b.push({id:"markers",fillalpha:"100",
items:h});for(b.push({id:"markerlabels",items:c});g;g-=1){d=null;f=a[g-1];k=f.id&&f.id.toLowerCase();if(f.mapItem=e=t[k]){if(f.shapeid)e.shapeObj=this.shapeObjs[f.shapeid.toLowerCase()];d=e.apply(f)}if(d)e._annotationIndex=h.length,i[k]=e,h.push(d.markerItem),d.markerLabel&&c.push(d.markerLabel)}d=null;if(this.options.markers.applyAll)for(g in t)if(!i[g]){if(e=t[g]){if(e.shapeid)e.shapeObj=this.shapeObjs[e.shapeid.toLowerCase()];d=e.apply(e)}if(d)e._annotationIndex=h.length,this.appliedMarkers[k]=
e,h.push(d.markerItem),d.markerLabel&&c.push(d.markerLabel)}};this.defineMarkersNShapes=function(){var b=this.mJSON.definition,a=this.mJSON.shapes,g,h,d;if(b&&b.length){if(a&&a.length)for(g=a.length;g;g-=1)if(h=a[g-1],d=h.id.toLowerCase())this.shapeObjs[d]=h;for(g=b.length;g;g-=1)if(h=b[g-1],d=h.id.toLowerCase()){a=new i(d,h,c);if(h.shapeid)a.shapeObj=this.shapeObjs[h.shapeid];this.items[d]=a}}};this.drawConnectors=function(){var a=this.options.connectors.showLabels,g=this.mJSON&&this.mJSON.connectors,
h=g&&g.length,c=[],d=[],e,f,t;if(h){b.push({id:"connectors",fillalpha:"100",items:c});for(b.push({id:"connectorLabels",fillalpha:"100",items:d});h--;)if(t=g[h],e=this.items[t.from.toLowerCase()],f=this.items[t.to.toLowerCase()],f=new l(t,e,f,this.rapi),e=f.computeConnectorJSON())c.push(e),e.label&&a&&d.push(f.getLabelJSON)}};this.destroy=function(){for(var b=this.items,a=b&&b.length||0;a--;)b[a].destroy();delete this.items;delete this.appliedMarkers;delete this.shapeObjs;delete this.connectors;delete this.options;
delete this.chart;this.group.destroy();delete this.group};this.setDefaultValues();this.defineMarkersNShapes();this.drawConnectors();this.applyMarkers()};l.prototype={computeConnectorJSON:function(){var g=this.api,h=this.options,c=this.from,d=this.to,b=h.link,f=h.label,u=e(h.showtooltip,this.showTooltip),i=u?h.tooltext:"",k=a(h.thickness,this.thickness),l=a(h.color,this.color),j=a(h.alpha,this.alpha),m=a(h.dashed,this.dashed),x=e(h.dashlen,this.dashlen),h=e(h.dashgap,this.dashgap),p;return!c||!d?null:
(p={fromMarkerId:c.id,toMarkerId:d.id},B({type:"line"},{x:c.definition.x,y:c.definition.y,tox:d.definition.x,toy:d.definition.y,dashed:m,dashlen:x,dashgap:h,link:b,tooltext:u?i:"",thickness:k,color:l,alpha:j,label:f,showshadow:this.shadow,onmouseover:function(b){M.raiseEvent("connectorrollover",p,g.chartInstance,b)},onmouseout:function(b){M.raiseEvent("connectorrollout",p,g.chartInstance,b)},onclick:function(b){M.raiseEvent("connectorclicked",p,g.chartInstance,b)}}))},getLabelJSON:function(){var a=
this.connectJSON;return B({type:"text"},{x:((Number(a.x)+Number(a.tox))/2).toString(),y:((Number(a.y)+Number(a.toy))/2).toString(),text:a.label,align:"center",valign:"middle",font:this.font,fontsize:this.fontsize,fontcolor:this.fontcolor,bgcolor:this.bgcolor,bordercolor:this.bordercolor,tooltext:this.tooltext})}};l.prototype.constructor=l;i.prototype={getMarkerOptions:function(){},getLabelAttrs:function(a,h,c,d,b){var e,f=a&&a.toLowerCase();this.getLabelAlignment[f]||(f="center");a=Number(c.x);e=
Number(c.y);c=d===void 0||b===void 0?c.radius||0:/^(top|bottom)$/ig.test(f)&&b*0.5||/^(left|right)$/ig.test(f)&&d*0.5||0;return this.getLabelAlignment[f](a,e,Number(c)+Number(h))},apply:function(g){g||(g={});var h=this.rapi,c=this._conf,d=h.translateX,b=h.translateY,f=this.definition,i=a(g.shapeid,f.shapeid),k=e(g.scale,f.scale,1),l=a(g.label,f.label)||"",j=a(g.labelpos,f.labelpos,"top").toLowerCase(),m=g.formattedValue===void 0?"":g.formattedValue,q=a(g.tooltext,f.tooltext)||(m?l+this.tooltipSepChar+
m:l),x=e(g.radius,f.radius,this.markerRadius)*k*this.autoScale||1.0E-4;if(i){i=i.toLowerCase();this.application=g;l=m?l+this.labelSepChar+m:l;isNaN(k)?k=1:k<0?k=0:k>5&&(k=5);f={x:f.x.toString(),y:f.y.toString(),fillcolor:a(g.fillcolor,g.color,this.fillColor),fillalpha:a(g.fillalpha,g.alpha,this.fillAlpha),fillratio:a(g.fillratio,this.fillRatio),fillangle:a(g.fillangle,this.fillAngle),borderthickness:e(g.borderthickness,this.borderThickness),bordercolor:a(g.bordercolor,this.borderColor),borderalpha:a(g.borderalpha,
this.borderAlpha),radius:x,tooltext:this.showMarkerTooltip?g.tooltext?g.tooltext:q:"",link:g.link,showshadow:e(g.showshadow,this.shadow),_markerLabel:l,_markerId:f.id,onmouseover:function(a){var g=a.data,c=g.options,g=g.bounds,e=c._markerRollOverArgs;if(!e)e=c._markerRollOverArgs={x:g.x1/g.xs,y:g.y1/g.ys,scaledX:g.x1,scaledY:g.y1,chartX:d+g.x1,chartY:b+g.y1,id:c._markerId,label:c._markerLabel};M.raiseEvent("markerrollover",e,h.chartInstance,a)},onmouseout:function(b){M.raiseEvent("markerrollout",
b.data.options._markerRollOverArgs,h.chartInstance,b)},onclick:function(b){M.raiseEvent("markerclicked",b.data.options._markerRollOverArgs,h.chartInstance,b)}};i==="triangle"?B(f,{type:"polygon",sides:3,startangle:this.startAngle}):i==="diamond"?B(f,{type:"polygon",sides:4,startangle:this.startAngle}):i==="arc"?B(f,{type:"arc",startangle:0,endangle:360,innerradius:x*0.6}):i==="circle"?f.type="circle":(i=this.getShapeArgs(),!i.radius&&(i.radius=this.markerRadius),i.radius*=k*this.autoScale,B(f,i));
if(f.type==="image")f.borderthickness=g.borderthickness||0,f.onload=function(b){var a=this.options,g=b.width,b=b.height,c=(Number(a.x)-g/(2*h.sFactor))*h.sFactor,a=(Number(a.y)-b/(2*h.sFactor))*h.sFactor,d;if(g&&b)for(d in{wrapper:1,tracker:1})this[d]&&this[d].attr({x:c,y:a,width:g,height:b})};if(!this.showMarkerLabels)return{markerItem:f};g=f.labelpadding||this.markerLabelPadding;j=this.getLabelAttrs(j,g,f);k=j.align;i=j.valign;m=c._labelBaseWidth;x=c._labelBaseHeight;q=c._labelXOffset;c=c._labelYOffset;
m=this.labelWrapWidth?this.labelWrapWidth:this.getWrapWidth[k](m,Number(j.x)+q);c=this.labelWrapHeight?this.labelWrapHeight:this.getWrapHeight[i](x,Number(j.y)+c);m>g&&(m-=g);c>g&&(c-=g);return{markerItem:f,markerLabel:B({type:"text"},{text:l,tooltext:f.tooltext,x:j.x,y:j.y,align:k,valign:j.valign,wrap:1,wrapwidth:m,wrapheight:c,fontsize:this.markerFontSize/h.sFactor,font:this.markerFont,fontcolor:this.markerFontColor})}}},setMarkerVisibility:function(a){var c=this.chart,c=c.options&&c.options.instanceAPI&&
c.options.instanceAPI.chartInstance;if(c=(c.__state&&c.__state.annotationGroupsById).markers.items[this._annotationIndex]){if(!this._origFill)this._origFill=Q({alpha:c.fillAlpha,color:c.fillColor,angle:c.fillAngle,ratio:c.fillRatio}),this._hideFill=Q({alpha:"0",color:c.fillColor,angle:c.fillAngle,ratio:c.fillRatio});a?c.wrapper.attr({fill:this._origFill}):c.wrapper.attr({fill:this._hideFill})}},getShapeArgs:function(){var a=B({},this.shapeObj),c;if(a){if(a.type==="polygon")a.sides<3?a.type="circle":
a.startangle=this.startAngle;else if(a.type==="arc")c=(a.radius||this.markerRadius)*this.autoScale,a.radius=c,a.innerradius=a.innerradius&&a.innerradius*this.autoScale||c*0.6;return a}else return null},destroy:function(){},getLabelAlignment:{top:function(a,c,d){return{x:a.toString(),y:(c-d).toString(),align:"center",valign:"top"}},left:function(a,c,d){return{x:(a-d).toString(),y:c.toString(),align:"right",valign:"middle"}},right:function(a,c,d){return{x:(a+d).toString(),y:c.toString(),align:"left",
valign:"middle"}},bottom:function(a,c,d){return{x:a.toString(),y:(c+d).toString(),align:"center",valign:"bottom"}},center:function(a,c){return{x:a.toString(),y:c.toString(),align:"center",valign:"middle"}}},getWrapWidth:{right:function(a,c){return c},left:function(a,c){return a-c},center:function(a,c){return o(c,a-c)*2}},getWrapHeight:{top:function(a,c){return c},middle:function(a,c){return o(c,a-c)*2},bottom:function(a,c){return a-c}}};i.prototype.constructor=i;d(k.eventList,{entityrollover:"FC_Event",
entityrollout:"FC_Event"});P("geo",{name:"(unknown)",revision:1,creditLabel:oa,standaloneInit:!1,charttopmargin:10,chartrightmargin:10,chartbottommargin:10,chartleftmargin:10,baseWidth:400,baseHeight:300,baseScaleFactor:1,defaultSeriesType:"geo",rendererId:"maps",entities:{},chart:function(c,d){B(this.dataObj.chart,{charttopmargin:this.dataObj.chart.maptopmargin,chartrightmargin:this.dataObj.chart.maprightmargin,chartbottommargin:this.dataObj.chart.mapbottommargin,chartleftmargin:this.dataObj.chart.mapleftmargin,
animation:this.dataObj.chart.animation||"0"});var f=this.dataObj,i=R(f,c,d,this),b=f.chart,l=i.chart,j=j=i[ia],n=l.useRoundEdges=e(b.useroundedges)===1,o=n?1:0,n=n?0:1,E=l.use3DLighting=e(b.use3dlighting,1)===1,s=B({},i.tooltip.style),q=new G(this.colorPaletteMap,(b.palette>0&&b.palette<6?b.palette:e(this.paletteIndex,1))-1),x=a(b.basefont,"Verdana"),p=U(b.basefontsize,10),v=a(b.basefontcolor,q.basefontcolor),y=U(b.outcnvbasefontsize,p),r=a(b.outcnvbasefont,x),C=y+"px",D=la(a(b.outcnvbasefontcolor,
v)),z=a(b.bgcolor,b.canvasbgcolor,q.canvasbgcolor),H=a(b.bgalpha,b.canvasbgalpha,q.canvasbgalpha),V,M;p+="px";v=la(v);this.realtimeEnabled&&this.postHCJSONCreation&&this.postHCJSONCreation.call(this,i);l.events.click=this.linkClickFN;j.numberFormatter=this.numberFormatter;B(j,{width:c,height:d,showTooltip:e(b.showtooltip,this.showtooltip,1),tooltipSepChar:a(b.tooltipsepchar,", "),showValues:e(b.showvalues,this.showValues,1),showCanvasBG:a(b.showcanvasbg,1),useValuesForMarkers:e(b.usevaluesformarkers,
0),outCanvasStyle:{fontFamily:r,color:D,fontSize:C},inCanvasStyle:{fontFamily:x,fontSize:p,color:v}});V=w(j.outCanvasStyle);M=w(j.inCanvasStyle);j.trendStyle=j.outCanvasStyle;j.showCanvasBG=="0"&&(H="0");var I=a(b.bordercolor,q.plotbordercolor),L=a(b.fillcolor,q.plotfillcolor),O=a(b.fillalpha,q.plotfillalpha),P=a(b.fillratio,q.plotfillratio),W=a(b.fillangle,q.plotfillangle),T=a(b.emptyentityfillcolor,b.emptyentitycolor,L);B(i,{chart:{emulateFlashGutter:e(b._emulateflashgutter,1),defaultSeriesType:this.defaultSeriesType,
paletteIndex:q.index,borderRadius:e(b.canvasborderradius,0),borderColor:S(a(b.canvasbordercolor,q.canvasbordercolor),a(b.canvasborderalpha,q.canvasborderalpha)),borderWidth:e(b.showcanvasborder,n)?e(b.canvasborderthickness,1):0,backgroundColor:Q({color:z,alpha:H,angle:a(b.bgangle,b.canvasbgangle,q.canvasbgangle),ratio:a(b.bgratio,b.canvasbgratio,q.canvasbgratio)}),plotBorderColor:"#ffffff",plotBorderWidth:0,plotBackgroundColor:Q({color:"#ffffff",alpha:0}),bgSWF:a(b.bgimage,b.bgswf),bgSWFAlpha:e(b.bgimagealpha,
b.bgswfalpha,100),bgImageScale:e(b.bgimagescale,100),bgImageDisplayMode:a(b.bgimagedisplaymode,"none").toLowerCase(),logoURL:X(b.logourl),logoPosition:a(b.logoposition,"tl").toLowerCase(),logoAlpha:e(b.logoalpha,100),logoLink:X(b.logolink),logoScale:e(b.logoscale,100),logoLeftMargin:e(b.logoleftmargin,0),logoTopMargin:e(b.logotopmargin,0),toolbar:function(){var g;var f={button:{}},i=f.button,j;i.scale=e(b.toolbarbuttonscale,1.15);i.width=e(b.toolbarbuttonwidth,15);i.height=e(b.toolbarbuttonheight,
15);i.radius=e(b.toolbarbuttonradius,2);i.spacing=e(b.toolbarbuttonspacing,5);i.fill=S(a(b.toolbarbuttoncolor,"ffffff"));i.labelFill=S(a(b.toolbarlabelcolor,"cccccc"));i.symbolFill=S(a(b.toolbarsymbolcolor,"ffffff"));i.hoverFill=S(a(b.toolbarbuttonhovercolor,"ffffff"));i.stroke=S(a(b.toolbarbuttonbordercolor,"bbbbbb"));i.symbolStroke=S(a(b.toolbarsymbolbordercolor,"9a9a9a"));i.strokeWidth=e(b.toolbarbuttonborderthickness,1);i.symbolStrokeWidth=e(b.toolbarsymbolborderthickness,1);j=i.symbolPadding=
e(b.toolbarsymbolpadding,5);i.symbolHPadding=e(b.toolbarsymbolhpadding,j);i.symbolVPadding=e(b.toolbarsymbolvpadding,j);j=f.position=a(b.toolbarposition,"tr").toLowerCase();switch(j){case "tr":case "tl":case "br":case "bl":break;default:j="tr"}i=f.hAlign=(""+b.toolbarhalign).toLowerCase()==="left"?"l":j.charAt(1);g=f.vAlign=(""+b.toolbarvalign).toLowerCase()==="bottom"?"b":j.charAt(0),j=g;f.hDirection=e(b.toolbarhdirection,i==="r"?-1:1);f.vDirection=e(b.toolbarvdirection,j==="b"?-1:1);f.vMargin=e(b.toolbarvmargin,
6);f.hMargin=e(b.toolbarhmargin,10);f.x=e(b.toolbarx,i==="l"?0:c);f.y=e(b.toolbary,j==="t"?0:d);return f}()},title:{text:ha(b.caption),offsetX:Number(b.captionxshift),offsetY:Number(b.captionyshift),position:a(b.captionposition,b.captionxshift!==void 0||b.captionyshift!==void 0?"top left":"top"),padding:e(b.captionpadding,10),style:{fontFamily:r,color:D,fontSize:y+3+"px",fontWeight:e(b.captionfontbold)===0?"normal":"bold"}},subtitle:{text:ha(b.subcaption),style:{fontFamily:r,color:D,fontSize:y+1+
"px",fontWeight:e(b.subcaptionfontbold)===0?"normal":"bold"}},orphanStyles:{defaultStyle:{style:B({},j.inCanvasStyle)}},tooltip:{enabled:j.showTooltip!==0,style:{fontFamily:x,fontSize:p,lineHeight:M,color:v,padding:e(b.tooltippadding,this.tooltippadding,3)+"px",backgroundColor:S(a(s.backgroundColor,b.tooltipbgcolor,q.tooltipbgcolor),a(b.tooltipbgalpha,"100")),borderColor:S(a(s.borderColor,b.tooltipbordercolor,q.tooltipbordercolor),a(b.tooltipborderalpha,"100")),borderWidth:e(b.tooltipborderthickness,
n)+"px",borderRadius:e(b.tooltipborderradius,o+1)+"px"},constrain:e(b.constraintooltip,1),shadow:e(b.showtooltipshadow,b.showshadow,1)?{enabled:!0,opacity:m(e(b.tooltipbgalpha,100),e(b.tooltipborderalpha,100))/100}:!1},legend:{itemStyle:{fontFamily:r,fontSize:C,lineHeight:V,color:D},itemHiddenStyle:{fontFamily:r,fontSize:C,lineHeight:V},enabled:e(b.showlegend,1),title:{text:ha(b.legendcaption),style:{fontFamily:r,fontSize:C,lineHeight:V,color:D}},position:a(b.legendposition,e(f.colorrange&&f.colorrange.gradient,
0)===0?"right":"bottom"),backgroundColor:a(b.legendbgcolor,q.bgcolor),backgroundAlpha:a(b.legendbgalpha,"100"),borderColor:a(b.legendbordercolor,q.legendbordercolor),borderThickness:a(b.legendborderthickness,"1"),borderAlpha:a(b.legendborderalpha,"100"),shadow:e(b.legendshadow,1),allowDrag:e(b.legendallowdrag,0),scroll:{scrollBgColor:a(b.legendscrollbgcolor,"AAAAAA"),scrollBtnColor:a(b.legendscrollbtncolor,"BBBBBB"),scrollBarColor:a(b.legendscrollbarcolor,"CCCCCC")},reversed:e(b.reverselegend,0),
interactive:e(b.interactivelegend,0),minColor:T,lighting3d:E},markers:{dataLabels:{style:{fontFamily:a(b.markerfont,x),fontSize:e(b.markerfontsize,parseInt(p,10)),fontColor:a(b.markerfontcolor,v)}},showTooltip:e(b.showmarkertooltip,j.showTooltip),showLabels:e(b.showmarkerlabels,b.showlabels,1),labelPadding:a(b.markerlabelpadding,"5"),labelWrapWidth:e(b.markerlabelwrapwidth,0),labelWrapHeight:e(b.markerlabelwrapheight,0),fillColor:a(b.markerfillcolor,b.markerbgcolor,q.markerbgcolor),fillAlpha:a(b.markerfillalpha,
q.markerbgalpha),fillAngle:a(b.markerfillangle,q.markerbgangle),fillRatio:a(b.markerfillratio,q.markerbgratio),fillPattern:a(b.markerfillpattern,q.markerbgpattern),borderThickness:a(b.markerborderthickness,1),borderColor:a(b.markerbordercolor,q.markerbordercolor),borderAlpha:e(b.markerborderalpha,q.markerborderalpha),radius:e(b.markerradius&&k.trimString(b.markerradius),7),shapeId:a(b.defaultmarkershape,"circle"),labelSepChar:a(b.labelsepchar,", "),tooltipSepChar:j.tooltipSepChar,autoScale:e(b.autoscalemarkers,
0),mapValueToRadius:e(b.mapmarkervaluetoradius,0),startAngle:e(b.markerstartangle,90),maxRadius:e(b.maxmarkerradius,0.3*c),minRadius:e(b.minmarkerradius,0.02*c),applyAll:e(b.applyallmarkers,0),shadow:e(b.showmarkershadow,b.showshadow,0)},connectors:{thickness:e(b.connectorthickness,b.markerconnthickness,"2"),color:a(b.connectorcolor,b.markerconncolor,q.markerbordercolor),alpha:a(b.connectoralpha,b.markerconnalpha,"100"),dashed:e(b.connectordashed,b.markerconndashed,0),dashLen:e(b.connectordashlen,
b.markerconndashlen,3),dashGap:e(b.connectordashgap,b.markerconndashgap,2),font:a(b.connectorfont,b.markerconnfont,x),fontColor:a(b.connectorfontcolor,b.markerconnfontcolor,v),fontSize:e(b.connectorfontsize,b.markerconnfontsize,parseInt(p,10)),showLabels:e(b.showconnectorlabels,b.showmarkerlabels,b.showlabels,1),labelBgColor:a(b.connectorlabelbgcolor,b.markerconnlabelbgcolor,q.plotfillcolor),labelBorderColor:a(b.connectorlabelbordercolor,b.markerconnlabelbordercolor,q.markerbordercolor),shadow:e(b.showconnectorshadow,
b.showmarkershadow,b.showshadow,0),showTooltip:e(b.showconnectortooltip,b.showmarkertooltip,j.showTooltip)},entities:{baseScaleFactor:this.baseScaleFactor,dataLabels:{style:{fontFamily:x,fontSize:p,lineHeight:M,color:i.plotOptions.series.dataLabels.color=v}},fillColor:L,fillAlpha:O,fillRatio:P,fillAngle:W,borderColor:I,borderAlpha:a(b.borderalpha,this.borderAlpha,"100"),borderThickness:e(b.showborder,1)?e(b.borderthickness,1):0,scaleBorder:e(b.scaleborder,0),hoverFillColor:a(b.hoverfillcolor,b.hovercolor,
q.plothoverfillcolor),hoverFillAlpha:a(b.hoverfillalpha,b.hoveralpha,q.plothoverfillalpha),hoverFillRatio:a(b.hoverfillratio,b.hoverratio,q.plothoverfillratio),hoverFillAngle:a(b.hoverfillangle,b.hoverangle,q.plothoverfillangle),hoverBorderThickness:a(b.hoverborderthickness),emptyEntityColor:T,emptyEntityAlpha:a(b.emptyentityfillalpha,b.emptyentityalpha,O),emptyEntityRatio:a(b.emptyentityfillratio,b.emptyentityratio,P),emptyEntityAngle:a(b.emptyentityfillangle,b.emptyentityangle,W),connectorColor:a(b.labelconnectorcolor,
b.connectorcolor,v),connectorAlpha:a(b.labelconnectoralpha,b.connectoralpha,"100"),useHoverColor:e(b.usehovercolor,1),hoverOnEmpty:e(b.hoveronempty,1),labelPadding:e(b.labelpadding,5),showLabels:e(b.showlabels,1),labelsOnTop:e(b.entitylabelsontop,1),includeNameInLabels:e(b.includenameinlabels,1),includeValueInLabels:e(b.includevalueinlabels,0),useSNameInTooltip:e(b.usesnameintooltip,0),useShortName:e(b.usesnameinlabels,1),labelSepChar:a(b.labelsepchar,", "),showTooltip:e(b.showentitytooltip,j.showTooltip),
tooltipSepChar:j.tooltipSepChar,valuesForMarkers:e(b.usevaluesformarkers,0),hideEmptyEntities:e(b.hideemptyentities,0),showHiddenEntityBorder:e(b.showhiddenentityborder,1),hiddenEntityColor:a(b.hiddenentitycolor,b.hiddenentityfillcolor,b.hiddenentityalpha||b.hiddenentityfillalpha?T:"ffffff"),hiddenEntityAlpha:a(b.hiddenentityalpha,b.hiddenentityfillalpha,0.001),shadow:e(b.showshadow,this.defaultPlotShadow,q.shadow)},entitydef:{useSNameAsId:e(b.usesnameasid,0)}});if(b.tooltipcolor)i.tooltip.style.color=
ra(b.tooltipcolor);if(a(b.clickurl)!==void 0)l.link=b.clickurl,l.style.cursor="pointer",ma&&(l.style._cursor="hand"),i.plotOptions.series.point.events.click=function(){l.events.click.call({link:b.clickurl})};j=l.bgImageDisplayMode;o=X(b.bgimagevalign,"").toLowerCase();n=X(b.bgimagehalign,"").toLowerCase();j=="tile"||j=="fill"||j=="fit"?(o!="top"&&o!="middle"&&o!="bottom"&&(o="middle"),n!="left"&&n!="middle"&&n!="right"&&(n="middle")):(o!="top"&&o!="middle"&&o!="bottom"&&(o="top"),n!="left"&&n!="middle"&&
n!="right"&&(n="left"));l.bgImageVAlign=o;l.bgImageHAlign=n;this.parseStyles(i);w(i.title.style);w(i.subtitle.style);w(i.tooltip.style);i.plotOptions.series.allowPointSelect=!0;this.parseExportOptions(i);this.preSeriesAddition&&this.preSeriesAddition(i,f,c,d);this.series&&this.series(f,i,this.name,c,d);this.postSeriesAddition&&this.postSeriesAddition(i,f,c,d);this.spaceManager(i,f,c,d);window.console&&window.FC_DEV_ENVIRONMENT&&window.console.log(i);return i},series:function(c,d){var f=this.numberFormatter,
i=this.hcJSON.series,b=this.dataObj,j=d[ia],l=b.colorrange,l=l&&l.color,n=d.legend,s=j.useValuesForMarkers?b.markers&&b.markers.application||[]:b.data,E={},v=function(b){for(var a,c,g=w&&w.length||0;g--;)if(a=w[g],c=Number(a.maxvalue),a=e(a.minvalue,d.colorRange.scaleMin),b>=a&&b<=c)return g;return null},q=Infinity,x=-Infinity,p,w,y,r;n.type=b.colorrange&&b.colorrange.gradient==="1"?"gradient":"point";r=s&&s.length||0;for(j._doNotShowLegend=!0;r--;)p=s[r],y=p.value,p.cleanValue=f.getCleanValue(y),
p.formattedValue=p.cleanValue!==null?f.dataLabels(y):void 0,p.origValue=y,p.cleanValue!==null&&(q=o(p.cleanValue,q),x=m(p.cleanValue,x));q===Infinity&&(q=void 0);x===-Infinity&&(x=void 0);d.colorRange=new k.colorRange({colorRange:b.colorrange,dataMin:q,dataMax:x,defaultColor:n.minColor,numberFormatter:f});r=(w=d.colorRange.colorArr)&&w.length||0;if(r>0){for(;r--;){p=w[r];if(j._doNotShowLegend&&(p.label!==""||p.label!==void 0))j._doNotShowLegend=!1;i.push({type:this.defaultSeriesType,showInLegend:!0,
data:[],plot:{},name:p.label,color:p.code,rangeMin:p.minvalue,rangeMax:p.maxvalue,allVisible:!0,allHidden:!1,visible:!0,legendClick:function(){var b;if(b=this.chart)!this.legend&&(this.legend=this.plot.legend),b.legendClick(this,!this.visible)},setVisible:function(b){var a=this.data,c=this.legendItem,g=this.visible;this.visible=b=b===void 0?!g:b;c&&n.colorizeItem&&n.colorizeItem(this,b);for(g=a&&a.length;g--;)(c=a[g].mapItem)&&(c.setMarkerVisibility?c.setMarkerVisibility(b):b?c.show&&c.show():c.hide&&
c.hide())}})}for(r=s&&s.length||0;r--;)if(p=s[r],b=v(e(p.value)),b!==null&&(f=n.type==="gradient"?d.colorRange.getColorObj(p.value).code:l&&l[b]&&a(l[b].color,l[b].code),E[b]||(E[b]=[]),f))p.color=p.color?p.color:f,E[b].push(p);i=i.reverse();for(r in E)i[r]&&(i[r].data=E[r])}else i.push({type:this.defaultSeriesType,data:s||[]});j._doNotShowLegend&&(this.hcJSON.legend.enabled=!1)},spaceManager:function(a,c,d,e){var b=a.chart,f=a[ia];f.smartLabel=this.smartLabel;var i=b.spacingLeft,j=b.spacingTop,l=
this.baseWidth,k=this.baseHeight;d-=b.spacingRight+i;b=e-(b.spacingBottom+j);e=f._captionBlock=this.manageTitleSpace(a,c,d,b);c=f._legendBlock=this.placeLegendBlock(a,c,d,b-e.height,e.isBottom?e.height:0);a=d-c.width;c=b-e.height-c.height;f=l/k;d=a/(l*this.baseScaleFactor);b=c/(k*this.baseScaleFactor);d>b?(d=b,i+=(a-c*f)/2,l=200/(k*d)):(j+=(c-a/f)/2,l=200/(l*d));/bottom/i.test(e.position)||(j+=e.height);this.scaleFactor=d;this.strokeWidth=l;this.translateX=i;this.translateY=j},placeLegendBlock:function(a,
c,d,e,b){var f=a.legend,i=a[ia],j=f.position.toLowerCase(),l={position:j};if(c.chart.showlegend==="0"||i._doNotShowLegend)return l.height=0,l.width=0,l;if(j==="bottom"){if(l.height=f.type==="gradient"?ka(a,c,d,e):aa(a,c,d,e),l.width=0,b)f.y=-b}else d/=2,l.width=f.type==="gradient"?ga(a,c,d,e):ea(a,c,d,e),l.height=0;return l},manageTitleSpace:function(a,c,d,e){var b=this.hcJSON,a=b.title,c=b.chart,b=b.subtitle,f=this.smartLabel,i=e/2,j=0,l=a.position.toLowerCase(),k=a.padding,m=!1,q=a.offsetX,n=a.offsetY,
p=0,o={},s,r;if(a.text===""&&b.text==="")return{height:0,position:l};if(!isNaN(q)||!isNaN(n))m=!0,q=isNaN(q)?0:q,n=isNaN(n)?0:n;s=a.text;if(s!==""){f.setStyle(a.style);r=f.getOriSize(s);if(r.width>d||r.height>i)r=f.getSmartText(s,d,i),a.text=r.text,r.tooltext&&(a.originalText=r.tooltext);a.height=p=r.height;j+=p}i-=j;s=b.text;if(s!==""){f.setStyle(b.style);r=f.getOriSize(s);if(r.width>d||r.height>i)r=f.getSmartText(s,d,i),b.text=r.text,r.tooltext&&(b.originalText=r.tooltext);j+=b.height=r.height}j+
k>i?j=i:j+=k;l.match(/left/)?(b.align=a.align="start",b.x=a.x=c.marginLeft):l.match(/right/)?(b.align=a.align="end",b.x=a.x=d):(b.align=a.align="middle",b.x=a.x=d/2);/bottom/.test(l)?(d=e-j+c.marginTop+k,a.y=d,b.y=d+p,m?(a.y+=n,b.y+=n,a.x+=q,b.x+=q):(c.marginBottom+=j,o.isBottom=!0)):m?(a.y+=n,b.y+=n,a.x+=q,b.x+=q):c.marginTop+=j;o.height=m?0:j;o.position=l;return o},getEntityPaths:function(){return this.entities},redefineEntities:function(a,c){var d=this.entities,e={},b={},f,i,j,l,k,m,n,o;for(n=
a.length;n--;)if(f=a[n],i=f.internalid,k=f.newid?f.newid:i,j=f.sname,f=f.lname,(l=d[i])&&!(k!==i&&d[k])){e[k]=k={origId:i};b[i]=!0;for(m in l)k[m]=l[m];k.shortLabel=j?j:l.shortLabel;k.label=f?f:l.label}this.entities={};for(o in e)e[o].origId=o,this.entities[o.toLowerCase()]=e[o];for(o in d)if(!b[o])for(m in k=d[o],c.useSNameAsId?(this.entities[k.shortLabel.toLowerCase()]=l={},l.origId=k.shortLabel):(this.entities[o.toLowerCase()]=l={},l.origId=o),k)l[m]=k[m]},colorPaletteMap:{basefontcolor:"foregroundcolor",
bordercolor:"foregrounddarkcolor",borderalpha:"foregrounddarkalpha",bgcolor:"backgroundlightcolor",bgalpha:"backgroundlightalpha",bgangle:"backgroundlightangle",bgratio:"backgroundlightratio",canvasbordercolor:"foregrounddarkcolor",canvasborderalpha:"foregrounddarkalpha",canvasbgcolor:"backgroundlightcolor",canvasbgalpha:"backgroundlightalpha",canvasbgangle:"backgroundlightangle",canvasbgratio:"backgroundlightratio",tooltipbordercolor:"foregrounddarkcolor",tooltipborderalpha:"foregrounddarkalpha",
tooltipbgcolor:"backgroundlightcolor",tooltipbgalpha:"backgroundlightalpha",tooltipfontcolor:"foregroundcolor",legendbordercolor:"foregrounddarkcolor",legendborderalpha:"foregrounddarkalpha",markerbordercolor:"foregroundlightcolor",markerborderalpha:"foregroundlightalpha",markerbgcolor:"backgrounddarkcolor",markerbgalpha:"backgrounddarkalpha",markerbgangle:"backgrounddarkangle",markerbgratio:"backgrounddarkratio",plotfillcolor:"backgroundcolor",plotfillalpha:"backgroundalpha",plotfillangle:"backgroundangle",
plotfillratio:"backgroundratio",plothoverfillcolor:"backgrounddarkcolor",plothoverfillalpha:"backgrounddarkalpha",plothoverfillangle:"backgrounddarkangle",plothoverfillratio:"backgrounddarkratio",plotbordercolor:"foregroundcolor",plotborderalpha:"foregroundalpha",shadow:"shadow"},eiMethods:{getMapName:function(){return this.jsVars.hcObj.logic.name},getEntityList:function(){var a=this.jsVars.hcObj,a=a.entities&&a.entities.items,c=[void 0],d,e,b;for(d in a)e=a[d],b=e.eJSON,c.push({id:e.id,originalId:e.originalId||
e.id,active:e.isVisible,lName:b.label,sName:b.shortLabel,value:e.value,formattedValue:e.formattedValue,toolText:e.toolText});return c},getDataAsCSV:function(){var a=this.jsVars,a=a.hcObj&&a.hcObj.entities&&a.hcObj.entities.items,c='"Id","Short Name","Long Name","Value","Formatted Value"',d,e,b,f;for(d in a)e=a[d],b=e.eJSON,f=e.value,c+='\r\n"'+e.id+'","'+b.shortLabel+'","'+b.label+'","'+(f===void 0?"":f)+'","'+e.formattedValue+'"';return c},getMapAttribute:function(){var a=this.jsVars.hcObj.fusionCharts;
M.raiseWarning(this,"12061210581","run","JavaScriptRenderer~getMapAttribute()",'Use of deprecated "getMapAttribute()". Replace with "getChartAttribute()".');return a.getChartAttribute.apply(a,arguments)},exportMap:function(){var a=this.jsVars.hcObj.fusionCharts;M.raiseWarning(this,"12061210581","run","JavaScriptRenderer~exportMap()",'Use of deprecated "exportMap()". Replace with "exportChart()".');return a.exportChart&&a.exportChart.apply(a,arguments)}}},P.linebase);O("renderer.maps",{drawGraph:function(){var a=
this.paper,c=this.layers,d,e,b;if(!this.options.nativeMessage){if(!c.dataset)c.dataset=a.group("dataset").insertAfter(c.background),c.tracker=a.group("hot").insertAfter(c.dataset);if(!this.shadowLayer)this.shadowLayer=c.shadow=a.group("shadow").insertBefore(c.dataset);this.strokeWidth=this.logic.strokeWidth;d=this.logic.scaleFactor;this.translateX=e=this.logic.translateX;this.translateY=b=this.logic.translateY;this.sFactor=d*this.logic.baseScaleFactor;this.transformStr=["t",e,",",b,"s",d,",",d,",0,0"].join("");
this.options.tooltip&&this.options.tooltip.enabled!==!1&&a.tooltip(this.options.tooltip.style,this.options.tooltip.shadow,this.options.tooltip.constrain);this.processEntityDefs();this.drawEntities();if(!ma||ba)c.dataset.attr({transform:this.transformStr}),c.shadow.attr({transform:this.transformStr});this.drawMarkers()}},setScaleRange:function(a,c){var g;for(var d=this.options,e=d[ia],b=e.useValuesForMarkers?this.markers:this.entities,f=b.items||b.appliedMarkers,e=e.useValuesForMarkers?{show:function(a){b.setMarkerVisibility(!0,
a)},hide:function(a){b.setMarkerVisibility(!1,a)}}:{show:function(a){a.show()},hide:function(a){a.hide()}},d=d.series,i=d.length,j,l,k,m;i--;)if(k=d[i],l=(j=k.data)&&j.length)if(k.rangeMin>=a&&k.rangeMax<=c){if(!k.allVisible)k.setVisible(!0),k.allVisible=!0}else if(k.rangeMax<a||k.rangeMin>c){if(!k.allHidden)k.setVisible(!1),k.allHidden=!0}else{k.allVisible=!1;for(k.allHidden=!1;l--;)k=j[l].id.toLowerCase(),g=(m=f[k])&&m.value,k=g,isNaN(k)||(k&&k>=a&&k<=c?e.show(m):e.hide(m))}},processEntityDefs:function(){var a=
this.logic,c=this.options.series,d=c&&c.length;for(a.redefineEntities(a.dataObj.entitydef||[],this.options.entitydef);d--;)c[d].chart=this},drawEntities:function(){var a=this.logic&&this.logic.dataObj&&this.logic.dataObj.data,c=this.layers.dataset,d=this.logic;this.eElems={};this.entities=new za(a,this,d,c)},drawMarkers:function(){var a=this.logic&&this.logic.dataObj||null;if(a=a&&a.markers||null)this.markerObjs=new Aa(a,{markers:this.options.markers,connectors:this.options.connectors},this,this.group);
this.options.entities.labelsOnTop||this.entities.drawLabels()}},O["renderer.root"])},[3,2,0,"release"]]);